### ISSUE TITLE
Scala Styleguide 작성

### ISSUE THREAD

**Issue by hyunminch** [Rainist/styleguide#2]
Scala Styleguide가 시급하네요~

**Comment by sunghyunzz** [comment]
`scalafmt` 설정도 함께 결정해서 명시하면 좋을 것 같습니다! 금요일에 간단히 얘기해볼까요?

**Comment by nitrogenice** [comment]
이번주는 바빠서... 다음주에 부탁드립니다. 서버 개발자들 다 모여서 얘기하죠~

**Comment by JungWinter** [comment]
스테일 이슈이므로 닫겠습니다. 추후 스칼라 스타일가이드가 필요하다고 생각되시는 분이 새롭게 이슈를 만들어 담당해 주세요!
