### ISSUE TITLE
Python Style Guide 제안

### ISSUE THREAD

**Issue by JungWinter** [Rainist/styleguide#5]
# Python Style Guide 제안

## 목적

Rainist 구성원이 파이썬 코드를 작성할 때 참고할 스타일 가이드를 작성하려는데 모두가 동의할 스타일가이드를 작성하기 위해 이슈로서 이견이 있을 수 있는 사항을 먼저 짚어보고자 합니다.

**스타일 가이드 제안은 리뷰어 모두의 만장일치를 전제로합니다.** 더불어 의견 수렴의 효율성을 높이기 위해 각 주제마다 제 개인적인 기호를 먼저 주장하고 있으며 당연히 이견이 있을 수 있음을 인지하고 있습니다. 각 주제에 대해 구성원 분들의 의견을 가감없이 말씀해 주길 바라며 일단 제일 이견이 있을만한 순서로 주제를 나열했습니다.

## Trailing comma

제 주장: 트레일링 콤마를 사용합니다.

트레일링 콤마를 사용하면 git diff를 볼 때 실질적으로 바뀐 부분에만 집중할 수 있으며 에디터에서 한 줄을 복제하거나 제거할 때 성가심을 줄여주고 실수를 방지합니다. 전사적으로 지금까지 트레일링 콤마를 사용하지 않았음을 알고 있지만 이로인해 [불필요한 추가 커밋과 실수](https://github.com/search?q=org%3ARainist+comma&type=Commits)가 지속적으로 발생하고 있으며 이는 구성원이 합의한 방식을 린트 도구에 반영해 줄여나가는게 맞다고 생각합니다.

```diff
 # non trailing comma
 def func(
-    hint: Optional[Dict[str, Any]] = None,
-    sort: Optional[Dict[str, Any]] = None
+    hint: Optional[Dict[str, Any]] = None
 )
```

```diff
 # with trailing comma
 def func(
     hint: Optional[Dict[str, Any]] = None,
-    sort: Optional[Dict[str, Any]] = None,
 )
```

```python
labels = [
    'apple',
    'crumble',
]
# a few moment later
labels = [
    'apple',
    'banana'  # <- New element with missing comma
    'crumble',
]
```

## Single quote, double quote

제 주장: double quote만 사용합니다.

사실 개인적으로는 모든 문자열을 single quote로, docstring만 double quote로 사용해왔습니다. 다만 이럴경우 린트 도구를 사용할 때 quote 검사를 예외사항으로 추가시켜주어야 하는데 이는 스타일 가이드를 따르는데 어려움만 높여주므로 하나로 통일해 사용해야한다고 생각했습니다. 그래서 docstring이 double quote인 김에 모두 double quote를 사용하도록 통일하는게 나을 것 같습니다.

* double quote를 사용할 땐 shift키를 눌러야 하므로 입력에 불편함이 있습니다.
* [PEP257](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring)은 "always use """triple double quotes""" around docstrings"으로 명시합니다.
* double quote를 사용하면 문자열 내 single quote로 apostrophe를 입력하기 쉽습니다.
* single quote를 사용하면 문자열 내 double quote로 대화를 인용하기 쉽습니다.
* [google styleguide](https://google.github.io/styleguide/pyguide.html#310-strings) 에서는 single이든 double이든 일관성있게 사용하도록 권장하며 `\\` 이스케이프를 피하기 위해 둘을 잠시 혼용하는걸 허용합니다.
* black 포매터는 double quote를 강제합니다.

## Line length

제 주장: 1줄은 80자까지 작성합니다.

코드를 작성하다보면 종종 80자를 넘어가곤 합니다. 그렇지만 1줄에 80자가 넘어가는 상황은 무언가 좋지 않다는 신호이며 max line length를 100자, 120자로 늘리는건 이런 코드 냄새에 관대해지게 만든다고 생각합니다. 깊은 indent, 긴 변수와 함수 이름, 깊숙한 곳에서의 import  때문에 80자를 넘기곤 하지만 이는 indent를 깊게 가져가지 말고 함수로 쪼개기, 여러 줄에 걸쳐 import 작성하기 등으로 리팩토링할 부분이지 관대함을 적용할 부분이 아니라 생각합니다. 더불어 80자 규칙은 린트 도구 도입으로 자동화할 수 있습니다.
PEP8의 언급에 따르면 파이썬 표준 라이브러리는 코드에 79자, 주석과 docstring에 72자를 사용하고 있지만 너무 보수적이라 생각하고 널리 받아들여질 수 있는 80자를 사용하는게 낫지 않을까 생각합니다.

## 네이밍

제 주장: PEP8을 따르고 클래스 이름은 온전하게, 함수 이름은 부분적으로 작성합니다.

`entities/fruits.py`내부의 클래스 이름으로 불필요한 중복으로 보여도 `Common`대신 `CommonFruit`을 사용합니다. 여러 저장소를 봤을 때 상위 모듈을 임포트해 네임스페이스와 같이 사용되기 보단 클래스 그 자체를 임포트해 사용하는 경향이 있으므로 클래스 그 자체로 스스로 설명가능한 이름이어야 한다고 생각합니다.

다만 함수명에 있어선 부분적인 이름이어도 괜찮다고 생각합니다. `common_fruit.py` 내부에선 컨텍스트를 공유하고 있으므로 `common_fruit.update_banana_common_fruit`보단 `common_fruit.update_banana` 혹은 더 분리해서 `common_fruit.banana.update`만으로도 충분하다고 생각합니다. 또 클래스와는 반대로 함수를 사용할 땐 함수를 임포트해 사용하기 보단 상위 모듈을 임포트해 네임스페이스와 같이 사용되는 경향을 보였습니다.

```python
# in common_fruits.py

# bad
def get_user_common_fruits():
    pass

# good
def get():
    pass

def update():
    pass
# ...
```

- 참고: [carrier-8percent 사례](https://github.com/Rainist/carrier-8percent/pull/2#discussion_r239337510)

## Assert와 If 문

제 주장: assert는 오로지 test 용으로만 사용합니다.

[assert statement](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement)는 문서에서 언급되었다시피 디버깅용 검사구문으로 의도되었습니다. `__debug__`과 함께 사용되는 if 문의 shortcut이며 이는 python을 실행할 때 `-O`(Optimize) 플래그와 함께 사용하면 모든 assert 구문을 무시하는 동작에서도 짐작할 수 있습니다. 그렇기 때문에 assert는 test 검증용으로 사용해야하며 유저가 어드민인지, 값이 제대로 들어 있는지 등 비즈니스 로직 상 검사하는 용도로 사용하지 않아야 한다고 생각합니다.

* 참고: [구글 파이썬 가이드 - Exception](https://google.github.io/styleguide/pyguide.html#244-decision)

## line break

제 주장: `\`보단 `()`를 사용합니다.

> 긴 줄을 래핑하는 가장 좋은 방법은 괄호, 대괄호 및 중괄호를 사용하는 것입니다. 긴 줄은 괄호로 묶어서 여러 줄로 나눠질 수 있습니다. 이 괄호들은 백 슬래시보다 우선적으로 사용되어야합니다. - [PEP8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)

## append와 +=, list comprehension

제 주장: `array += [other]`보단 `array.append(other)`를, `append`보단 list comprehension 사용합니다.

언어적 차원에서 보다 편한 문법을 제공하므로 마땅히 이를 사용해야 한다고 생각합니다.

```python
In [1]: %%timeit
   ...: a = []
   ...: for i in range(1_000_000):
   ...:     a += [str(i)]
   ...:
268 ms ± 8.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [2]: %%timeit
   ...: a = []
   ...: for i in range(1_000_000):
   ...:     a.append(str(i))
   ...:
252 ms ± 2.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %%timeit
   ...: a = [str(i) for i in range(1_000_000)]
   ...:
212 ms ± 4.01 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

## indent style

제 주장: 함수 선언 줄이 80자가 넘어간다면 1줄에 1인자씩 적어주고 마지막 인자 뒤 트레일링 콤마를 붙이고 Parentheses를 다음 줄에서 닫아줍니다.

auto formatter중 하나인 black의 기본 동작이기도 합니다.

```python
def func(
    if_some_variables: Optional[List[str]],
    over_the_80_width: Optional[int],
    separate_lines: bool = True,
) -> int:
    return 42

def foo(short: int) -> None:
    pass
```

## Lint tool

- [x] [pylint](https://www.pylint.org/): eslint처럼 작성된 파이썬 코드에 잘못된 부분은 없는지, 더 개선시킬 부분은 없는지 자동으로 검사해주는 린트 도구입니다. [`.pylintrc`](https://github.com/Rainist/banksalad-riders-bigvalue/blob/develop/.pylintrc) 파일을 통해 세부적인 옵션을 조정할 수 있습니다.
- [x] [isort](https://github.com/timothycrosley/isort): import order를 자동으로 정렬해주는 도구입니다. [`.editorconfig`](https://github.com/Rainist/banksalad-riders-bigvalue/blob/develop/.editorconfig#L13-L21) 혹은 `.isort.cfg`로 세부적인 옵션을 조정할 수 있습니다.
- [ ] [black](https://github.com/ambv/black): auto formatter 중 하나입니다. [medium 아티클](https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505)를 참고하시면 다른 포매터도 있지만 black을 제안하는 이유는 따로 설정해줘야할 부분이 적으며 위에서 주장한 스타일에 가장 근접하게 동작하는 도구이기 때문입니다. 다만 포매터라는 것이 기호가 있을 수 있는 부분이며 없어도 충분히 Rainist의 스타일 가이드에 맞는 코드를 작성할 수 있기에 이는 개인에 판단에 맡겨 사용하는 도구로 제안하고자합니다.
- [ ] [mypy](http://mypy-lang.org/): 파이썬 스태틱 타입 검사 도구입니다. TypeScript처럼 변수, 함수 등에 타입 힌트를 부여할 수 있으며 이를 기반으로 잘못된 코드가 없나 검사합니다. 참고로 파이썬의 타입 힌트는 런타임에 영향을 끼치지 않습니다. 기존 몇몇 레포에서 mypy를 적극적으로 사용해보고자 하는 시도가 있었으나 경험 부족으로 타입으로 커버하기 힘들어지는 케이스들이 발생하였고 결국 Any로 처리하거나 mypy를 제거하는 사례가 있었습니다. 그래서 이는 개인의 판단에 맡겨 사용하는게 좋을 것 같습니다.

## Pre commit hook

위에서 결정된 lint 도구들을 커밋 작성 전에 실행되는 git pre commit hook에 설정하여 완전히는 아니더라도 잦은 스타일 코드 리뷰, 실수 등을 줄이고자 합니다. [최근 진행된 프로젝트 중 하나](https://github.com/Rainist/banksalad-riders-bigvalue/blob/develop/bin/pre-commit)에서 시범적으로 도입했었고 lint에러나 스타일 지적이 줄어드는 효과를 보였습니다.

## 테스트 코드

기본적인 테스트 코드를 [pytest](https://docs.pytest.org/en/latest/)를 이용해 작성하길 제안합니다. TDD와 integration test까지는 아니어도 각 함수의 동작을 테스트하는 unit test만이라도 작성한다면 좀 더 명세에 맞게 검증된 코드를 짤 수 있다고 생각합니다.

pytest는 파이썬 기본 내장 unittest에 비해 간결하고 깔끔한 테스트 코드를 작성할 수 있으며 더 읽기 쉬운 에러 리포트를 출력하며 fixture기능을 적극적으로 활용할 수 있고 여러 플러그인 또한 지원됩니다.

참고: [unittest와 pytest를 비교해보는 글](https://blog.daftcode.pl/the-cleaning-hand-of-pytest-28f434f4b684)

## Abbreviation and Acronym, 축약어와 두문자어

* PascalCase 혹은 camelCase 사용시에 다음의 규칙을 적용합니다.
* 축약어는 모두 첫 글자만 대문자
	* 예) simpleApp (application), currentMax (maximum)
	* 단 2글자 축약어는 모두 대문자
		* 예) userID (identity)
* 두문자어는 모두 대문자
	* 예) HTTP, HTML, URL, DB, UUID, JSON, IO
	* 예) URLBuilder, IOStream, HTTPClient
* 다양한 케이스 바이 케이스 규칙을 적용하기 보단 간결한 규칙을 적용해버리는게 낫다고 생각합니다.

## 버저닝

* [시맨틱 버저닝](https://semver.org/lang/ko/): `3.6.5`, `1.10.24`
* [캘린더 버저닝](https://calver.org/): `18.10.01`, `16.04`
* 기존 레포들은 시맨틱 버저닝을 기준으로 작성되어 왔습니다. 라이브러리를 작성한다면 각 버전 업데이트가 어떤 의미를 가지고있는지 파악하기 쉬운 시맨틱 버저닝이 어울린다 생각하지만 웹 서버에 캘린더 버저닝을 사용하면 어떨까 생각해봤습니다.
* 캘린더 버저닝은 주로 정기적인 릴리즈 프로세스를 갖는 프로젝트에 쓰이고 있으나 또 릴리즈 날짜가 유의미한 프로젝트(pytz, certifi)에도 사용되고 있습니다.
* 클라이언트와의 협업에 있어 시맨틱 버저닝이 어울린다라는 생각과 동시에 outdated된 서버를 파악하고 주시하기엔 캘린더 버저닝이 유용하지 않을까라는 생각을 갖고 있습니다.
* 이 부분은 따로 주장하는 부분은 없습니다.

## 기타사항

* [PEP8](https://www.python.org/dev/peps/pep-0008/)을 준수합니다.
* [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html)를 참고합니다.
* 매직 밸류는 상수로 선언합닌다.
* 전역 변수를 사용하지 않습니다.
	* `app`, `db`, `config`등의 변수들을 실행시켜줘야 할 때는 `main()`함수를 선언한 뒤 그 안에서 사용합니다.
* 상수에 `__contains__`할 땐 상수를 set으로 사용합니다.
	* e.g. `value in {1, 2, 3}`

### 버전

* Python 3.6 이상을 사용합니다.
* 마이너 업데이트가 있을 시 첫 패치 업데이트 이후 사용합니다.
	* 예) 3.7 버전은 3.7.1 이후로 사용

### 문서화

* 최소한 Repo의 Description과 간단한 README를 작성합니다.
* 굳이 한 곳(Backend wiki, Confluence 등)에 모으기 보단 일단 해두기라도 하자 라는데 공감합니다

---

긴 제안 읽어주셔서 감사하며 본 이슈는 PR과 분리되어 진행됩니다. 이 이슈에서 구성원들의 합의가 이루어진 뒤 세부적인 파일작성, config 파일이 포함된 내용 등이 PR에 올라갑니다.

**Comment by AhnSeongHyun** [comment]
전체적으로 동의합니다. 네이밍의 함수명에 대한 부분은 실제 코드상에서 리뷰로 맞춰 나가면서 동기화가 필요할 것 같습니다. 추가적으로 requirements.txt 의 운영/개발로 나누는 정책 그리고 pipenv 에 대한 부분도 다루어졌으면 좋겠습니다. 스타일 가이드의 범위보다 조금 넓을 수 있지만 충분히 논의 가능할 것 같습니다.

**Comment by cardia** [comment]
저도 전체적으로 동의합니다. 이렇게 확실히 정하는 것이 이해하는데 많이 도움이 될 것 같습니다.

**Comment by sean-ahn** [comment]
전반적으로 좋구요,
추가로 `__init.py__` 를 어떻게 활용할건지 논의가 있었으면 좋겠어요.

**Comment by Min3953** [comment]
1. 클래스 명과 함수명 모두 온전하게 적는게 저는 좋을거 같습니다.
다른 모듈에서 함수를 가져와 사용할때,
```
import module
module.func()
```
보다는
```
from module import func
func()
```
요런식으로 사용하여 FP스럽게 코드를 작성할 수 있을거 같습니다. 그리고 후자와 같이 코딩을 진행할때 클래스명 및 함수명 모두 온전하게 적어야 효율적이라 생각이 듭니다. 물론 class의 method는 부분적으로 naming하여도 무방할거 같습니다.

2. max char length는 79자 그대로 가져가는게 괜찮을거 같습니다.
겨울님께서
```
PEP8의 언급에 따르면 파이썬 표준 라이브러리는 코드에 79자, 주석과 docstring에 72자를 사용하고 있지만 너무 보수적이라 생각하고 널리 받아들여질 수 있는 80자를 사용하는게 낫지 않을까 생각합니다.
```
라고 언급해 주셨는데, 79자와 80자는 큰 차이가 없을 뿐만 아니라 79자로 가져가는게 어떤부분에서 보수적이며 80자는 왜 널리 받아들여질 수 있는지 공감이 크게되지 않아 기존에 사용하고 있고 파이썬 표준에서 79자로 정해놓은걸 따르는게 좋지 않나 생각해 봅니다.

**Comment by JungWinter** [comment]
@AhnSeongHyun `requirements.txt`와 `requirements-dev.txt` 두개로만 나누면 어떨까요? prod 관련 의존성들은 전자에, lint, test, 로컬 dev에 필요한 의존성들(pytest, pylint, isort 등)은 후자에 두는게 깔끔할 것 같습니다. 일부 패턴에선 `requirements/prod.txt` 같은 식으로 관리하긴 하나 전 두 파일에 모두 의존성을 표시할 수 있고 `requirements-prod.txt`, `requirements-test.txt` 또한 같은 맥락으로 굳이 세분화하지 않고 프로덕션 환경 서버 구동에 필요한 의존성 / 그 외 의존성 으로 나누는게 좋지 않을까 생각합니다.

`pipenv`, `virtualenv` 관련된 내용은 사실 "`pipenv`만 씁시다!"라고 주장하지 않는 이상 의존성 관리 팁 중 하나로 옵셔널하게 소개되면 좋을 것 같습니다. 마찬가지로 `pipenv`를 사용할 때 아직 `pip install -r Pipfile.lock`같은 기능이 지원되지 않는 이상 `Pipfile`, `Pipfile.lock`만 올리기 보단 표준 패키지 매니저와의 호환성을 유지해 `requirements.txt`도 같이 올리면 좋을 것 같습니다.

---

@sean-ahn Python 3.3 이상부터 파이썬이 패키지를 인식할 때 `__init__.py`이 없어도 import할 폴더를 패키지 중 일부로 인식하는데요 실험해 본 결과 다음과 같은 현상이 나타납니다.

```
test/
  foo/
  └── bar.py
  main.py
```
```python
# bar.py
def baz():
    pass
```
```python
# main.py
import foo
foo.bar.baz()
# AttributeError: module 'foo' has no attribute 'bar'

import foo.bar
foo.bar.baz()

from foo import bar
bar.baz()

from foo.bar import baz
baz()
# Ok
```

만약 `__init__.py` 없이 작성한다면 이 점에 유의해서 작성해야 할 것 같습니다. 더불어 해당 모듈에 공통적으로 사용되는 함수들을 `__init__.py`에 작성하곤 했는데 이 부분에 어떤 대안이 있을까요?

---

@Min3953 1번에서 말씀해 주신 것처럼 모듈을 가져오는게 아닌 모듈의 함수를 가져와 사용할 때 함수 이름에 모듈의 의미가 포함되어있어야 효율적임에 공감합니다. (예를 들면 `from data.repository.actual_assets import get_user_actual_assets`) 여기에 두 가지 측면을 더 논의하고 싶은게 있다면 함수형 프로그래밍스러운 코드와 클린 아키텍쳐 구조입니다.

저는 함수형 프로그래밍을 격리된 사이드 이펙트, 이뮤터블한 자료구조 활용, 순수 함수의 채용, 선언적 프로그래밍을 중심으로 한 패러다임이라고 생각합니다. 그래서 민규님이 말씀하신 부분은 모듈이 아닌 모듈의 함수를 가져와 사용한다면 더 함수 자체에 집중할 수 있다는 FP의 의미같은데 맞게 이해한걸까요? 다만 네이밍적으로 함수가 깔끔해지냐 아니냐, `module.func()`과 `func_of_module()`중 무엇이 더 깔끔하다고 판단할지는 또 다른 문제라고 생각합니다.

더불어 제가 주로 봤던 파이썬 서버 구조에선 클린 아키텍쳐를 적극적으로 채용하고 있습니다. 그러다 보니 `import data.repository.actual_assets as repository`로 가져와 `repository.get_user_actual_assets` 처럼 사용하는 식의 통일된 컨텍스트 구조를 많이 봐왔습니다. 이 때 이미 `presentation.views.actual_assets.controller.py` 안에선 actual assets 이라는 컨텍스트로 공유되고 있는 상황인데 여기에서 또 `repository.get_user_actual_assets`로 사용하는게 불필요한 중복으로 느껴졌습니다.

2번에서 79자와 80자가 큰 차이 없다고 말씀해 주셨는데 사실 저도 1글자 차이를 그렇게 크다고 느끼진 않습니다. 또 지금 찾아보니 flake8은 79자가 기본, pycodestyle도 79자가 기본으로 설정되어있네요. 다만 널리 받아들여진다고 언급했던 이유는 제가 이 제안을 작성할 때 참고했던 린트 도구가 pylint (기본 80자), yapf (80) black (80 + 10%) 여서 그랬고 JS, 루비, 리눅스 커널 개발쪽에서 통용되는 max line length가 80이어서 그렇게 표현했었습니다. 후자는 파이썬이 아니니 논외고 저희가 무슨 도구를 사용하든 max line length는 지정할 수 있으므로 파이썬 표준에서 정해놓은 79자를 사용하자는데 저도 동의합니다.

**Comment by AhnSeongHyun** [comment]
전적으로 동의합니다. requirements.txt, requirements-dev.txt 로만 나누면 좋을것 같습니다. 의존성 관리 툴에 대한 부분은 옵션으로 가져가되 가이드 식으로 정리되면 좋을것 같습니다.

**Comment by sunghyunzz** [comment]
내용에 대체로 동의하고 그동안 회색 영역에 있던 것들을 잘 정리해주셔서 너무 좋습니다.👍👍 하나 얘기해보고 싶은 건 문자열 처리를 double quote로 가져가자는 의견인데요. 저는 문자열을 double/single quote 중 무엇을 사용하는지를 굳이 lint 해야할 필요가 없다고 느껴서 이는 스타일 가이드에서 다루지 않아도 될 것 같은데요. 혹시 어떤 상황에서 위와 같은 스타일 가이드가 도움이 될지 좀 더 설명 부탁드리겠습니다. 🙏🙏

**Comment by JungWinter** [comment]
@sunghyunzz 저는 single/dougle quote 둘 중 하나를 쓰자! 보다는 적어도 한 레포엔 하나의 스타일로 통일되어야한다고 생각했습니다. 이 부분에 과학적 근거가 있는건 아니고 가독성과 일관성을 위해서 최소한의 가이드 라인이라고 생각했습니다. 다만 기존에 이미 둘을 섞어서 쓰여졌던 레포나 이를 일일이 신경쓰기 번거로움이 있을까 싶어 둘 중 하나를 선택해서 레포 전체에 일관성 있게 사용하되 결정이 어렵다면 docstring이 double인 김에 모두 double로 쓰자, 마침 black 포매터도 기본 동작이 double 이다. 라는 생각에 주장했었습니다.

새롭게 정리하면 `single quote, double quote에 관해선 각자가 판단해 사용합니다. 한 레포엔 하나의 quote 스타일을 사용합니다.` 가 되겠네요!
재정의한 주장에 대해선 어떻게 생각하시나요?

---

또 버저닝에 관해서도 더 얘기하고싶습니다. 예를 들면 어느 서버에서 `0.16.5` 라는 시맨틱 버저닝을 따르고 있을 경우 1. 이 버저닝이 유의미 한지 2. 누구에게 왜 유의미 한지 가 의문입니다.

시맨틱 버저닝을 따르는 이유는 버전만 보고도 어떤 범위의 변화가 생겼는지(브레이킹 체인지가 발생했는지, 버그 패치 업데이트인지) 알 수 있기 때문이었고 이로 인해 보통의 라이브러리 등은 시맨틱 버저닝을 사용했습니다. 다만 이를 서버까지 적용해야 할까 생각이 듭니다. 서버가 `0.16.0`에서 `1.0.0`이 된다면 어떤 이유일까 의문이었고 클라이언트와는 `v1`, `v5`등으로 명시적으로 API 버저닝을 하고 있는데 오히려 캘린더 버저닝을 사용한다면 이 서버가 얼마나 오랫동안 업데이트가 안되고 있었는지 파악 가능해서 더 유의미하지 않을까 생각합니다.

@Choani 광우님 의견은 어떠신가요?

**Comment by Choani** [comment]
`quote`에 관해서는 `repo`안에서 일관적으로 사용 하면 충분 할 것 같습니다. (겨울님 마지막 코멘트 의견에 동의합니다)

시맨틱 버저닝에 관해서는 일반적으로 `Major.Minor.Patch` 로 쓰는 걸로 알고 있습니다.

Minor, Patch는 잘 지키고 있는 것 같습니다. (기능 추가, 기능 변경)

Major에 관해서 더 합의를 하고 그것에 맞게 버저닝을 하면 좋을 것 같습니다.

Major = 0 일 경우는 아직 서비스 전
Major = 1 일 경우는 서비스 중
Major = 2 일 경우는 1과 호환이 안되는 버전

Minor가 올라가는 경우는 새로운 기능이 추가가 되었을 때

Patch가 올라가는 경우는 기능 변경이 있을 때

이런식으로 버저닝이 되면 현재 서비스 중인지 여부 + 개발 여부도 같이 알 수 있을 것 같습니다.

얼마나 오랫동안 업데이트가 안된지는 release note를 보면 업데이트 날짜를 알 수 있으므로 크게 의미가 없다고 생각합니다.

---

그런데 버저닝이 python style guide와 같이 묶이는 이슈인가요? 글을 쓰고 보니 python과는 별개의 이슈라고 생각이 드네용 👀 

@JungWinter

**Comment by FlouieInCl** [comment]
저는 __init__.py 가 필요하다고 생각합니다.
만약, 사용하지 않는다면 겨울님 말씀대로 유의해야 할 점이 생겨 실수를 유발할 수 있습니다.
저의 경우도 지금까지 해당 패키지에서 공통으로 사용하는 함수들을 작성하는 용도로 __init__.py 를 사용해 왔고, 일반적인 헬퍼함수 이외에도 뷰 데코레이터, base class, __all__ 등 패키지 내에서 공통으로 필요한 것들을 담는데 제격이라고 생각됩니다 :)
