### ISSUE TITLE
Python Sanic 컨벤션 내용 추가

### ISSUE THREAD

**Issue by JungWinter** [Rainist/styleguide#9]
서버에서 `HTTPStatus`만 응답하고 싶을 때 아래 3개의 방식 중 **두번째 방식**을 이용한다.

1. `response.raw(b’’, status=HTTPStatus.NO_CONTENT)`
2. **`response.json(None, status=HTTPStatus.NO_CONTENT)`**
3. `response.json({}, status=HTTPStatus.NO_CONTENT)`

## 레퍼런스

* [Sanic #1113](https://github.com/huge-success/sanic/pull/1113)
* [Sanic #1102](https://github.com/huge-success/sanic/issues/1102)

**Comment by devholic** [comment]
`Accept` Header 값에 따라 `Content-Type`을 설정하는건 어떨까요?

**Comment by JungWinter** [comment]
거의 모든 곳에서 json 통신하는걸로 알아서 레포마다 개발자가 알아서 판단해 사용하면 될거같은데 어떤 내용을 추가하고 싶으신거에영?

**Comment by devholic** [comment]
🤔 모든 서비스에서 `json`을 통해 통신한다고 가정하는 것 보다 `Accept` 값에 따라서 그에 맞는 응답 형태로 내려주는게 적합할 것 같아서용

**Comment by JungWinter** [comment]
그럼 가이드 수준으로 Accept 헤더에 맞는 `response` 함수를 사용(`text`, `raw`, `json`, `html`)을 권장한다는 내용을 넣으면 될까요?

**Comment by devholic** [comment]
넹~

**Comment by JungWinter** [comment]
추가됨
